app = "discord-path-api"      # set your app name
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"   # this Dockerfile is in server/

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[processes]
  # Runs inside /app/server per Dockerfile WORKDIR
  app = "python app.py"
  # If you use gunicorn instead, set:
  # app = "gunicorn -b 0.0.0.0:5000 app:app --workers 2 --threads 4 --timeout 60"
